#!/usr/bin/env bash
#
# deploys this to the path directory
#
# yes, work could be added to the path, but felt it better
# to deploy to my bin/groovy folder, which is on PATH.
# This, links to my dropbox, so should be available at
# client sites if allowed to connect to Dropbox. Otherwise,
# I will just have to copy it from my Dropbox account.
#
# cp work ~/Dropbox/groovyscripts/
cp work ~/.work
cp newwork ~/.work
chmod u=rwx,g=rx,o=rx ~/.work/work
chmod u=rwx,g=rx,o=rx ~/.work/newwork

echo "Add ~/.work to your PATH"
