#!/usr/bin/env bash
#
TO=$1

case "$OSTYPE" in
  solaris*) echo "SOLARIS - not yet implemented." ;;
  darwin*)  open -a Terminal $TO ;;
  linux*)   x-terminal-emulator -e "cd $TO; $SHELL" ;;
  bsd*)     echo "BSD - not yet implemented." ;;
  msys*)    echo "WINDOWS - not yet implemented." ;;
  *)        echo "unknown: $OSTYPE" ;;
esac
