= WORKMAN - A Directory Switcher
Bill Turner
:toc:
:toc-placement!:

toc::[]

== Purpose
To easily switch terminal to different project homes.


== Motivation
I often prefer working from the command line. Being a long time consultant,
on many projects, sometimes many within one bigger project, or _homes_ for
many working directories within a project, it is nice to be able to have
a reminder to relevant directories. I use this at home, too, for I have many
projects scattered about diverse directory hierarchies. For example, I have
most of my code within a folder called _workspace_, and this contains many
other, unrelated projects. Similarly, I have top level folders for _presentations_,
_writing_, and others. It is easy for me to get confused. ;-)

This tool helps not only identify projects, but will also:

. launch a new terminal at saved project locations
. easily remember alias names for projects
. tags for projects to help remember what the project tooling is or other salient aspects
. listing all projects
. filtered listing by tag(s)
. listing of tags

NOTE: as I write this, not all of these features are implemented. Likewise, the documentation
herein could be out of date. It is always best to refer to the _help_, or just read the code.

== Getting Started
=== Linux Installation
_not yet implemented_

=== Mac Installation
_not yet implemented_

=== Windows Installation
_not yet implemented_

== Running Workman
You run Workman with the following command:

`$ work`

Run without options, the directory will change to the most recently
used project alias. If no alias has been set, the directory will not change.

`work --save`

The save option saves the current path to the list of known work locations
using the final segment of the path as the alias. If said alias exists, it will be suffixed.

`work --save <project alias>`

Adding a project alias after the save option adds the current path to the list of known
work locations with the specificed project alias.

`work <project alias>`

Changes the directory to the location of the directory associated with the project alias.

`work --list`

Lists the known work locations, showing both the alias and the corresponding path.

`work --rename <existing project alias> <new project alias>`

Renames the existing project alias to the new alias. If the new alias exists, it will be
suffixed. If the existing project alias does not exist, no change occurs.

`work -h --help`

Displays usage help.
